# -*- coding: utf-8 -*-
"""FinalAgenttt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qyjBLnAfyXeYvfwSOMU2uUvu5y_IKjSB
"""

"""
RECHERCHE SÉMANTIQUE AVEC GÉNÉRATION DE REQUÊTES PAR LLM - GROQ CLOUD
Domaine : Biologie animale, génomique, conservation
Fonctionnalité : Recherche web avec Firecrawl
"""

import requests
import time
import json
import xml.etree.ElementTree as ET
from typing import List, Dict, Optional, Tuple
from datetime import datetime
import urllib.parse
import re
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from qdrant_client import QdrantClient
from qdrant_client.models import (
    Distance,
    PayloadSchemaType,
    PointStruct,
    VectorParams,
)
import uuid
import os
from functools import lru_cache
from pathlib import Path

from dotenv import load_dotenv

# ============================================
# 0. CONFIGURATION (.env)
# ============================================
#
# Every credential and every deployment-specific value is read from the
# environment. Nothing secret is hardcoded here: this file is committed, the
# .env next to it is not (see .gitignore).
#
# The .env is addressed by absolute path rather than by walking up from the
# working directory. This subagent can be started from the repository root or
# from backend/, and a bare load_dotenv() would then pick up backend/.env -
# which has none of these keys - and the module would silently fall back to
# unconfigured defaults.
#
# There is one .env for the whole agent, at the Literature_Agent root. This
# subagent used to carry its own alongside it, which is how it ended up with a
# different QDRANT_API_KEY than the rest of the agent for the same cluster.
#
# Lookup order, first hit wins:
#   1. the process environment (docker/compose, CI secrets)
#   2. the Literature_Agent .env

_HERE = Path(__file__).resolve().parent
load_dotenv(_HERE.parents[1] / ".env", override=False)


def _env(name: str, default: str = "") -> str:
    """Read a setting, tolerating the `KEY = "value"` style used in some of
    the sibling .env files (dotenv keeps the quotes only when they are
    unbalanced, but stray whitespace still slips through)."""
    return (os.getenv(name) or default).strip().strip('"').strip("'")


# --- Qdrant -----------------------------------------------------------------
QDRANT_URL = _env("QDRANT_URL")
QDRANT_API_KEY = _env("QDRANT_API_KEY")
COLLECTION_NAME = _env("QDRANT_COLLECTION", "lina_researchPaperArticles")
VECTOR_SIZE = int(_env("QDRANT_VECTOR_SIZE", "384"))

# --- Groq Cloud -------------------------------------------------------------
GROQ_API_KEY = _env("GROQ_API_KEY")
GROQ_API_URL = _env("GROQ_API_URL", "https://api.groq.com/openai/v1/chat/completions")
GROQ_MODEL = _env("GROQ_MODEL", "openai/gpt-oss-20b")

HEADERS = {
    "Authorization": f"Bearer {GROQ_API_KEY}",
    "Content-Type": "application/json",
}

# --- Firecrawl --------------------------------------------------------------
FIRECRAWL_API_KEY = _env("FIRECRAWL_API_KEY")
FIRECRAWL_BASE_URL = _env("FIRECRAWL_BASE_URL", "https://api.firecrawl.dev/v1")

# --- Embeddings -------------------------------------------------------------
EMBEDDING_MODEL = _env("EMBEDDING_MODEL", "paraphrase-multilingual-MiniLM-L12-v2")

# Settings that must be present before the agent can do anything useful.
REQUIRED_SETTINGS = ("QDRANT_URL", "QDRANT_API_KEY", "GROQ_API_KEY", "FIRECRAWL_API_KEY")


def missing_settings() -> List[str]:
    """Names of the required settings that are not configured."""
    return [n for n in REQUIRED_SETTINGS if not globals().get(n)]


# The client is built on first use, never at import time. Constructing it here
# would make a missing or wrong QDRANT_URL an ImportError that no caller can
# catch - the same reasoning as subagents/writing/kb/qdrant_setup.py.
@lru_cache(maxsize=1)
def get_qdrant() -> QdrantClient:
    if not QDRANT_URL:
        raise RuntimeError(
            "QDRANT_URL is not set - copy .env.example to .env in the "
            "Literature_Agent root and fill it in. This subagent has no .env "
            "of its own; the agent keeps a single settings file."
        )
    return QdrantClient(url=QDRANT_URL, api_key=QDRANT_API_KEY or None)


def setup_collection() -> None:
    """Create the collection and its payload index if they do not exist yet.

    Called from main(); never at import. It only ever creates - it does not
    drop an existing collection, so running the agent cannot destroy the
    indexed corpus.
    """
    client = get_qdrant()
    if not client.collection_exists(COLLECTION_NAME):
        client.create_collection(
            collection_name=COLLECTION_NAME,
            vectors_config=VectorParams(size=VECTOR_SIZE, distance=Distance.COSINE),
        )
        print(f"✅ Collection '{COLLECTION_NAME}' créée (dimension {VECTOR_SIZE})")

    try:
        client.create_payload_index(
            collection_name=COLLECTION_NAME,
            field_name="type",
            field_schema=PayloadSchemaType.KEYWORD,
        )
    except Exception:
        pass  # already indexed

# ============================================
# 3. CONFIGURATION DES APIS
# ============================================

class Config:
    """Configuration des APIs"""
    # Firecrawl
    FIRECRAWL_API_KEY = FIRECRAWL_API_KEY
    FIRECRAWL_SEARCH_URL = f"{FIRECRAWL_BASE_URL}/search"
    FIRECRAWL_SCRAPE_URL = f"{FIRECRAWL_BASE_URL}/scrape"

    # APIs académiques (gardées)
    OPENALEX_URL = "https://api.openalex.org/works"
    PUBMED_SEARCH_URL = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi"
    PUBMED_FETCH_URL = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi"
    CROSSREF_URL = "https://api.crossref.org/works"
    SEMANTIC_URL = "https://api.semanticscholar.org/graph/v1/paper/search"

# ============================================
# 4. GÉNÉRATEUR DE REQUÊTES PAR LLM
# ============================================





class QueryGenerator:
    """
    Génère des requêtes de recherche optimisées via Groq
    """

    def __init__(self):
        self.cache = {}

    def generate_queries(self, user_query: str, num_queries: int = 5) -> Dict:
        """
        Génère des requêtes de recherche à partir de la requête utilisateur
        """
        print(f"\n🧠 GÉNÉRATION DE REQUÊTES PAR LLM")
        print("="*60)
        print(f"📝 Requête utilisateur: {user_query}")
        print("="*60)

        cache_key = f"{user_query}_{num_queries}"
        if cache_key in self.cache:
            print("   ✅ Requêtes récupérées du cache")
            return self.cache[cache_key]

        try:
            messages = [
                {
                    "role": "system",
                    "content": """Tu es un expert en recherche d'information scientifique.
                    À partir de la requête de l'utilisateur, génère des requêtes de recherche optimisées.

                    Règles :
                    - 5 requêtes variées et complémentaires
                    - Utilise des opérateurs de recherche (AND, OR, "")
                    - Inclut des synonymes et termes associés
                    - Adapte les requêtes pour différents moteurs de recherche
                    - Optimise pour la recherche académique et web

                    Retourne UNIQUEMENT un JSON valide."""
                },
                {
                    "role": "user",
                    "content": f"""Génère {num_queries} requêtes de recherche pour :
                    "{user_query}"

                    Format JSON attendu :
                    {{
                        "main_topic": "sujet principal",
                        "domain": "domaine scientifique",
                        "search_queries": [
                            "requête 1",
                            "requête 2",
                            "requête 3",
                            "requête 4",
                            "requête 5"
                        ],
                        "keywords": ["mot1", "mot2", "mot3"],
                        "synonyms": ["synonyme1", "synonyme2"],
                        "secondary_concepts": ["concept1", "concept2"]
                    }}"""
                }
            ]

            payload = {
                "model": GROQ_MODEL,
                "messages": messages,
                "max_tokens": 500,
                "temperature": 0.4,
                "top_p": 0.9
            }

            print("   ☁️ Appel à Groq...", end="", flush=True)
            response = requests.post(GROQ_API_URL, headers=HEADERS, json=payload, timeout=45)

            if response.status_code == 429:
                print(" ⏳ Rate limit, attente...")
                time.sleep(5)
                return self.generate_queries(user_query, num_queries)

            response.raise_for_status()
            result = response.json()
            content = result["choices"][0]["message"]["content"]
            print(" ✅")

            # Extraction du JSON
            try:
                content = re.sub(r'<think>.*?</think>', '', content, flags=re.DOTALL).strip()
                if content.startswith("```json"):
                    content = content[7:]
                if content.endswith("```"):
                    content = content[:-3]
                content = content.strip()

                queries_data = json.loads(content)

                if not queries_data.get("search_queries"):
                    queries_data["search_queries"] = [user_query]

                queries_data["search_queries"] = queries_data["search_queries"][:num_queries]

                if user_query not in queries_data["search_queries"]:
                    queries_data["search_queries"].insert(0, user_query)

                self.cache[cache_key] = queries_data

                print(f"\n📋 REQUÊTES GÉNÉRÉES:")
                for i, q in enumerate(queries_data["search_queries"], 1):
                    print(f"   {i}. {q}")

                if queries_data.get("keywords"):
                    print(f"\n🔑 Mots-clés: {', '.join(queries_data['keywords'][:5])}")

                if queries_data.get("secondary_concepts"):
                    print(f"📌 Concepts: {', '.join(queries_data['secondary_concepts'][:3])}")

                return queries_data

            except json.JSONDecodeError as e:
                print(f"   ⚠️ Erreur parsing JSON: {e}")
                queries = re.findall(r'"([^"]+)"', content)
                if queries:
                    return {
                        "main_topic": user_query,
                        "domain": "sciences",
                        "search_queries": queries[:num_queries],
                        "keywords": [],
                        "synonyms": [],
                        "secondary_concepts": []
                    }
                else:
                    return {
                        "main_topic": user_query,
                        "domain": "sciences",
                        "search_queries": [user_query],
                        "keywords": [],
                        "synonyms": [],
                        "secondary_concepts": []
                    }

        except Exception as e:
            print(f"   ❌ Erreur génération requêtes: {e}")
            return {
                "main_topic": user_query,
                "domain": "sciences",
                "search_queries": [user_query],
                "keywords": [],
                "synonyms": [],
                "secondary_concepts": []
            }

# ============================================
# 5. MOTEUR DE RECHERCHE FIRECRAWL
# ============================================

class FirecrawlSearchEngine:
    """
    Moteur de recherche utilisant l'API Firecrawl
    """

    def __init__(self):
        self.api_key = Config.FIRECRAWL_API_KEY
        self.headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json"
        }

    def search(self, query: str, limit: int = 3) -> List[Dict]:
        """
        Recherche sur le web avec Firecrawl
        """
        results = []

        print(f"\n🌐 RECHERCHE WEB (FIRECRAWL)")
        print("="*50)
        print(f"📝 Requête: {query}")

        try:
            # Appel à l'API Firecrawl
            payload = {
                "query": query,
                "limit": limit,
                "scrapeOptions": {
                    "formats": ["markdown", "html"],
                    "onlyMainContent": True
                }
            }

            response = requests.post(
                Config.FIRECRAWL_SEARCH_URL,
                headers=self.headers,
                json=payload,
                timeout=30
            )

            if response.status_code == 200:
                data = response.json()

                # Vérification du format de réponse Firecrawl
                if data.get("success") and data.get("data"):
                    for item in data["data"]:
                        # Firecrawl retourne les résultats avec markdown, title, url, etc.
                        title = item.get("title", "Titre inconnu")
                        description = item.get("description", "")
                        url = item.get("url", "")
                        markdown = item.get("markdown", "")
                        content = item.get("content", "")

                        # Prend le meilleur contenu disponible
                        abstract = description or markdown[:500] or content[:500] or ""

                        if abstract:
                            results.append({
                                "source": "Firecrawl",
                                "title": title,
                                "abstract": abstract[:500],
                                "url": url,
                                "type": "web",
                                "full_content": markdown or content,
                                "raw_data": item
                            })

                print(f"   ✅ {len(results)} résultats trouvés")

            else:
                print(f"   ⚠️ Erreur Firecrawl: {response.status_code}")
                print(f"   Réponse: {response.text[:200]}")

        except requests.exceptions.Timeout:
            print("   ⚠️ Timeout Firecrawl")
        except Exception as e:
            print(f"   ⚠️ Erreur Firecrawl: {e}")

        return results

    def scrape_url(self, url: str) -> Optional[Dict]:
        """
        Scrape une URL spécifique avec Firecrawl
        """
        try:
            payload = {
                "url": url,
                "formats": ["markdown", "html"],
                "onlyMainContent": True
            }

            response = requests.post(
                Config.FIRECRAWL_SCRAPE_URL,
                headers=self.headers,
                json=payload,
                timeout=30
            )

            if response.status_code == 200:
                data = response.json()
                if data.get("success") and data.get("data"):
                    return data["data"]

            return None

        except Exception as e:
            print(f"   ⚠️ Erreur scraping: {e}")
            return None

# ============================================
# 6. RECHERCHE ACADÉMIQUE (GARDÉE)
# ============================================

class AcademicSearchEngine:
    """Moteur de recherche académique"""

    def search_openalex(self, query: str, limit: int = 3) -> List[Dict]:
        """Recherche sur OpenAlex"""
        results = []
        try:
            params = {
                "search": query,
                "filter": "publication_year:2020-2025",
                "per_page": limit,
                "sort": "cited_by_count:desc"
            }
            response = requests.get(Config.OPENALEX_URL, params=params, timeout=30)
            response.raise_for_status()
            data = response.json()

            for paper in data.get("results", []):
                abstract = self._extract_abstract(paper)
                if abstract:
                    results.append({
                        "source": "OpenAlex",
                        "title": paper.get("title", "Titre inconnu"),
                        "abstract": abstract,
                        "authors": self._extract_authors(paper),
                        "year": paper.get("publication_year", "N/A"),
                        "citations": paper.get("cited_by_count", 0),
                        "doi": paper.get("doi", "").replace("https://doi.org/", ""),
                        "url": paper.get("doi", ""),
                        "concepts": self._extract_concepts(paper),
                        "type": "academic"
                    })

        except Exception as e:
            print(f"   ⚠️ OpenAlex: {e}")

        return results

    def _extract_abstract(self, paper):
        abstract_index = paper.get("abstract_inverted_index")
        if not abstract_index:
            return ""
        words = {}
        for word, positions in abstract_index.items():
            for pos in positions:
                words[pos] = word
        return " ".join(words[i] for i in sorted(words.keys()))

    def _extract_authors(self, paper):
        authors = []
        for auth in paper.get("authorships", []):
            nom = auth.get("author", {}).get("display_name", "")
            if nom:
                authors.append(nom)
        return authors[:5]

    def _extract_concepts(self, paper):
        concepts = []
        for concept in paper.get("concepts", [])[:3]:
            concepts.append(concept.get("display_name", ""))
        return concepts



# ============================================
# 7bis. CACHE SÉMANTIQUE (QDRANT)
# ============================================

from qdrant_client.models import Filter, FieldCondition, MatchValue

def chercher_similaire_qdrant(query_embedding: np.ndarray, seuil: float = 0.6, type_recherche: str = "article"):
    """
    Cherche dans Qdrant un résultat déjà stocké et sémantiquement proche
    de la requête. Filtre par type ('article' ou 'synthese') pour éviter
    de mélanger les deux formats de payload.
    """
    try:
        query_filter = Filter(
            must=[
                FieldCondition(key="type", match=MatchValue(value=type_recherche))
            ]
        )

        resultats = get_qdrant().query_points(
            collection_name=COLLECTION_NAME,
            query=query_embedding.tolist(),
            query_filter=query_filter,
            limit=1
        ).points
    except Exception as e:
        print(f"   ⚠️ Erreur recherche Qdrant: {e}")
        return None

    if resultats and resultats[0].score >= seuil:
        return resultats[0]
    return None
# ============================================
# 7. MOTEUR D'EMBEDDINGS
# ============================================

from sentence_transformers import SentenceTransformer

# Chargé UNE SEULE FOIS, à la première utilisation - jamais à l'import.
# Ce module est sur la chaîne d'import de l'agent Literature : le construire
# ici téléchargerait ~500 Mo de poids à chaque démarrage du service, y compris
# sur les routes qui ne font aucune recherche sémantique.
# Modèle multilingue : comprend le français, l'anglais, etc.
@lru_cache(maxsize=1)
def get_model() -> SentenceTransformer:
    return SentenceTransformer(EMBEDDING_MODEL)

class SemanticEmbeddingEngine:
    """Moteur d'embeddings sémantiques (vrais embeddings neuronaux)"""

    def __init__(self):
        self.model = get_model()
        self.embedding_cache = {}

    def generate_embeddings(self, text: str) -> np.ndarray:
        """Génère un embedding sémantique (capture le sens, pas juste les mots)"""
        cache_key = text[:200]
        if cache_key in self.embedding_cache:
            return self.embedding_cache[cache_key]
        try:
            embedding = self.model.encode(text, normalize_embeddings=True)
            self.embedding_cache[cache_key] = embedding
            return embedding
        except Exception as e:
            print(f"   ⚠️ Erreur embedding: {e}")
            return np.zeros(384)

    def semantic_similarity(self, embedding1: np.ndarray, embedding2: np.ndarray) -> float:
        """Similarité cosinus entre deux embeddings sémantiques"""
        if embedding1 is None or embedding2 is None:
            return 0.0
        try:
            similarity = np.dot(embedding1, embedding2)
            return float(max(0, min(1, similarity)))
        except:
            return 0.0

    def stocker_meilleur_resultat(self, user_query: str, results: list, seuil: float = 0.6):
        """
        Calcule les scores sémantiques pour tous les résultats.
        Génère un résumé Groq pour CHAQUE résultat.
        Stocke dans Qdrant uniquement ceux dont le score dépasse le seuil.
        """
        if not results:
            print("⚠️ Aucun résultat à traiter")
            return []

        results = calculer_scores_semantiques(user_query, results, self)
        stockes = []

        for result in results:
            titre = result.get("title", "")
            abstract = result.get("abstract", "")
            score = result.get("relevance_score", 0)

            print(f"\n📝 Résumé en cours pour: {titre} (score: {score:.3f})")
            resume = generer_resume_groq(abstract, titre)
            result["resume"] = resume

            if score > seuil:
                texte = f"{titre} {abstract}"
                embedding = self.generate_embeddings(texte)

                point = PointStruct(
                    id=str(uuid.uuid4()),
                    vector=embedding.tolist(),
                    payload={
                        "title": titre,
                        "resume": resume,
                        "url": result.get("url", ""),
                        "source": result.get("source", ""),
                        "query_used": user_query,
                    }
                )

                get_qdrant().upsert(collection_name=COLLECTION_NAME, points=[point])
                stockes.append({"title": titre, "resume": resume, "score": score})
                print(f"✅ Stocké dans Qdrant (score: {score:.3f})")
            else:
                print(f"⏭️ Score sous le seuil ({seuil}) — résumé généré mais non stocké")

        print(f"\n📊 {len(stockes)}/{len(results)} résultats stockés dans Qdrant")
        return results


# ============================================
# 8. RECHERCHE UNIFIÉE AVEC LLM
# ============================================

class UnifiedSearchWithLLM:
    """
    Recherche unifiée avec :
    1. Génération de requêtes par LLM
    2. Recherche Firecrawl
    3. Recherche académique
    4. Embeddings sémantiques
    5. Classement par pertinence
    """

    def __init__(self):
        self.query_generator = QueryGenerator()
        self.firecrawl_engine = FirecrawlSearchEngine()
        self.academic_engine = AcademicSearchEngine()
        self.semantic_engine = SemanticEmbeddingEngine()




    def search(self, user_query: str, limit: int = 5) -> Dict:
        """
        Recherche complète avec génération de requêtes par LLM
        """
        print(f"\n🔍 RECHERCHE UNIFIÉE AVEC LLM")
        print("="*70)

        # ÉTAPE 0: Vérification du cache sémantique (Qdrant)
        print("\n🗄️ ÉTAPE 0: Vérification du cache sémantique (Qdrant)")
        print("-"*50)
        query_embedding = self.semantic_engine.generate_embeddings(user_query)
        cache_hit = chercher_similaire_qdrant(query_embedding, seuil=0.6)

        if cache_hit:
            print(f"   ✅ Résultat similaire déjà en cache (score: {cache_hit.score:.3f})")
            print("   ⏭️ Web search et OpenAlex ignorés — utilisation du cache")

            payload = cache_hit.payload
            result_cache = {
                "source": payload.get("source", "Cache Qdrant"),
                "title": payload.get("title", ""),
                "abstract": payload.get("resume", ""),
                "resume": payload.get("resume", ""),
                "url": payload.get("url", ""),
                "type": "cache",
                "relevance_score": cache_hit.score,
                "query_used": user_query,
            }

            return {
                "query_data": {
                    "search_queries": [user_query],
                    "keywords": [],
                    "secondary_concepts": []
                },
                "results": [result_cache],
                "total_found": 1,
                "from_cache": True
            }

        print("   ℹ️ Aucun résultat similaire en cache — recherche complète en cours")

        # ÉTAPE 1: Génération des requêtes par LLM
        print("\n📝 ÉTAPE 1: Génération des requêtes")
        print("-"*50)
        queries_data = self.query_generator.generate_queries(user_query)

        # ÉTAPE 2: Recherche avec Firecrawl
        print("\n🔍 ÉTAPE 2: Recherche web (Firecrawl)")
        print("-"*50)
        all_results = []

        for i, query in enumerate(queries_data["search_queries"][:3], 1):
            print(f"\n📌 Requête {i}: {query}")
            results = self.firecrawl_engine.search(query, limit=2)
            for result in results:
                result["query_used"] = query
                result["query_priority"] = i
            all_results.extend(results)

        # ÉTAPE 3: Recherche académique
        print("\n📚 ÉTAPE 3: Recherche académique")
        print("-"*50)
        academic_results = self.academic_engine.search_openalex(user_query, limit=2)
        for result in academic_results:
            result["query_used"] = user_query
            result["query_priority"] = 0
        all_results.extend(academic_results)
        print(f"   ✅ {len(academic_results)} résultats académiques")

        # ÉTAPE 4: Classement sémantique
        print("\n🧠 ÉTAPE 4: Classement sémantique")
        print("-"*50)

        for result in all_results:
            text = f"{result.get('title', '')} {result.get('abstract', '')}"
            result_embedding = self.semantic_engine.generate_embeddings(text)
            score = self.semantic_engine.semantic_similarity(query_embedding, result_embedding)
            result["relevance_score"] = score

        all_results.sort(key=lambda x: x.get("relevance_score", 0), reverse=True)

        # Élimination des doublons
        seen_titles = set()
        unique_results = []
        for result in all_results:
            title = result.get("title", "").lower()
            if title not in seen_titles and title:
                seen_titles.add(title)
                unique_results.append(result)





        print("\n📊 ÉTAPE 5: Statistiques")
        print("-"*50)
        print(f"   📝 Requêtes générées: {len(queries_data['search_queries'])}")


        return {
            "query_data": queries_data,
            "results": unique_results[:limit],
            "total_found": len(unique_results)
        }

# ============================================
# 9. GÉNÉRATION DE RÉSUMÉ (GROQ)
# ============================================

def generer_resume_groq(texte: str, titre: str = "") -> str:
    """Génère un résumé avec Groq"""
    if not texte or len(texte) < 20:
        return "Texte trop court pour un résumé."

    if len(texte) > 4000:
        texte = texte[:4000]

    messages = [
        {
            "role": "system",
            "content": """Tu es un expert en biologie animale et génomique.
            Résume l'article en français (150-250 mots) avec :
            1. Contexte et problématique
            2. Méthodes principales
            3. Résultats clés
            4. Implications et conclusions"""
        },
        {
            "role": "user",
            "content": f"""Résume : {titre if titre else ''}\n\n{texte}"""
        }
    ]

    payload = {
        "model": GROQ_MODEL,
        "messages": messages,
        "max_tokens": 400,
        "temperature": 0.3
    }

    try:
        response = requests.post(GROQ_API_URL, headers=HEADERS, json=payload, timeout=45)

        if response.status_code == 429:
            time.sleep(5)
            return generer_resume_groq(texte, titre)

        response.raise_for_status()
        result = response.json()
        return result["choices"][0]["message"]["content"].strip()

    except Exception as e:
        print(f"   ❌ Erreur Groq: {e}")
        return texte[:300] + "..."



def generer_synthese_groq(resultats_top: List[Dict]) -> str:
    """Fusionne les résumés des meilleurs résultats en une synthèse unique via Groq"""
    if not resultats_top:
        return "Aucun résultat à synthétiser."

    blocs = []
    for r in resultats_top:
        titre = r.get("title", "")
        resume = r.get("resume", "") or r.get("abstract", "")
        blocs.append(f"### {titre}\n{resume}")

    texte_source = "\n\n".join(blocs)

    messages = [
        {
            "role": "system",
            "content": """Tu es un expert en biologie animale et génomique.
            À partir des résumés d'articles fournis, rédige UNE SEULE synthèse
            cohérente en français (200-300 mots) qui :
            1. Dégage les points communs et convergences entre les sources
            2. Met en avant les résultats/méthodes les plus significatifs
            3. Souligne les éventuelles divergences ou nuances entre sources
            4. Conclut sur l'état des connaissances du sujet"""
        },
        {
            "role": "user",
            "content": f"Voici les résumés à synthétiser :\n\n{texte_source}"
        }
    ]

    payload = {
        "model": GROQ_MODEL,
        "messages": messages,
        "max_tokens": 500,
        "temperature": 0.3
    }

    try:
        response = requests.post(GROQ_API_URL, headers=HEADERS, json=payload, timeout=45)
        if response.status_code == 429:
            time.sleep(5)
            return generer_synthese_groq(resultats_top)
        response.raise_for_status()
        result = response.json()
        content = result["choices"][0]["message"]["content"].strip()
        content = re.sub(r'<think>.*?</think>', '', content, flags=re.DOTALL).strip()
        return content
    except Exception as e:
        print(f"   ❌ Erreur Groq (synthèse): {e}")
        return "Erreur lors de la génération de la synthèse."

# ============================================
# 10. AFFICHAGE
# ============================================

def display_results(result_data: Dict):
    """Affiche tous les résultats, avec le score du meilleur résultat en en-tête"""

    query_data = result_data.get("query_data", {})
    results = result_data.get("results", [])

    if not results:
        print("\n❌ Aucun résultat trouvé")
        return

    best_score = max((r.get("relevance_score", 0) for r in results), default=0)

    print("\n" + "="*70)
    print(f"📚 RÉSULTATS DE LA RECHERCHE")
    print(f"🏆 Meilleur score de pertinence: {best_score:.2%}")
    print("="*70)

    # Affichage des requêtes générées
    print("\n📋 REQUÊTES GÉNÉRÉES PAR LLM:")
    for i, q in enumerate(query_data.get("search_queries", []), 1):
        print(f"   {i}. {q}")

    if query_data.get("keywords"):
        print(f"\n🔑 Mots-clés: {', '.join(query_data['keywords'][:5])}")

    if query_data.get("secondary_concepts"):
        print(f"📌 Concepts: {', '.join(query_data['secondary_concepts'][:3])}")

    print(f"\n📊 {len(results)} résultats les plus pertinents")
    print("="*70)


    for i, result in enumerate(results, 1):
        score = result.get("relevance_score", 0)
        stars = "⭐" * int(score * 5) if score > 0 else "⭐⭐⭐"
        marqueur = " 🏆" if score == best_score else ""

        print(f"\n{'='*60}")
        print(f"📄 RÉSULTAT {i} | Pertinence: {score:.2%} {stars}{marqueur}")
        print(f"{'='*60}")

        print(f"📌 {result.get('title', 'N/A')}")
        print(f"📚 {result.get('source', 'N/A')}")
        print(f"🔍 Requête utilisée: {result.get('query_used', 'N/A')}")

        if result.get('type') == 'academic':
            print(f"📅 {result.get('year', 'N/A')}")
            if result.get('citations', 0) > 0:
                print(f"📊 {result.get('citations', 0)} citations")
            if result.get('doi'):
                print(f"🔗 DOI: https://doi.org/{result['doi']}")
        else:
            if result.get('url'):
                url = result['url'][:80] + "..." if len(result['url']) > 80 else result['url']
                print(f"🔗 {url}")


        abstract = result.get('abstract', '')
        resume = result.get('resume')
        if not resume and abstract and len(abstract) > 50:
            resume = generer_resume_groq(abstract, result.get('title', ''))

        if resume:
            print(f"\n📝 RÉSUMÉ:")
            print("-" * 50)
            for j in range(0, len(resume), 100):
                print(f"   {resume[j:j+100]}")
            print("-" * 50)
        elif abstract:
            print(f"\n📝 EXTRAIT:")
            print("-" * 50)
            print(f"   {abstract[:300]}...")
            print("-" * 50)




def display_synthese(result_data: Dict, semantic_engine, top_n: int = 3):
    """Génère les résumés des top_n meilleurs résultats, affiche et stocke leur synthèse"""
    results = result_data.get("results", [])
    if not results:
        print("\n❌ Aucun résultat trouvé")
        return

    query_used = result_data.get("query_data", {}).get("search_queries", ["N/A"])[0]

    # Tri par score décroissant et sélection des meilleurs
    results_tries = sorted(results, key=lambda x: x.get("relevance_score", 0), reverse=True)
    top_resultats = results_tries[:top_n]

    # Génère les résumés manquants
    for r in top_resultats:
        if not r.get("resume"):
            abstract = r.get("abstract", "")
            if abstract and len(abstract) > 50:
                r["resume"] = generer_resume_groq(abstract, r.get("title", ""))

    best_score = top_resultats[0].get("relevance_score", 0)

    print("\n" + "="*70)
    print(f"📚 SYNTHÈSE DES MEILLEURS RÉSULTATS")
    print(f"🏆 Score le plus élevé: {best_score:.2%}")
    print("="*70)

    print(f"\n📌 Sources utilisées pour la synthèse ({len(top_resultats)}):")
    for r in top_resultats:
        score = r.get("relevance_score", 0)
        ref = r.get("doi") and f"https://doi.org/{r['doi']}" or r.get("url", "N/A")
        print(f"   • {r.get('title', 'N/A')} — {score:.2%}")
        print(f"     🔗 {ref}")

    print("\n📝 SYNTHÈSE:")
    print("-" * 50)
    synthese = generer_synthese_groq(top_resultats)
    for j in range(0, len(synthese), 100):
        print(f"   {synthese[j:j+100]}")
    print("-" * 50)


    stocker_synthese_qdrant(query_used, synthese, top_resultats, semantic_engine)






def stocker_synthese_qdrant(user_query: str, synthese: str, top_resultats: List[Dict], semantic_engine):
    """
    Stocke la synthèse générée dans Qdrant, avec les titres et références
    des articles/sources utilisés pour la générer.
    """
    if not synthese or synthese.startswith("Erreur") or synthese.startswith("Aucun"):
        print("⏭️ Synthèse invalide, non stockée dans Qdrant")
        return None


    sources = []
    for r in top_resultats:
        titre = r.get("title", "N/A")
        if r.get("type") == "academic" and r.get("doi"):
            reference = f"https://doi.org/{r['doi']}"
        else:
            reference = r.get("url", "N/A")

        sources.append({
            "title": titre,
            "reference": reference,
            "source_type": r.get("source", "N/A"),
            "score": round(r.get("relevance_score", 0), 3)
        })


    texte_embedding = f"{user_query} {synthese}"
    embedding = semantic_engine.generate_embeddings(texte_embedding)

    point = PointStruct(
        id=str(uuid.uuid4()),
        vector=embedding.tolist(),
        payload={
            "type": "synthese",
            "query_used": user_query,
            "synthese": synthese,
            "sources": sources,
            "nb_sources": len(sources),
            "date": datetime.now().isoformat()
        }
    )

    try:
        get_qdrant().upsert(collection_name=COLLECTION_NAME, points=[point])
        print(f"✅ Synthèse stockée dans Qdrant avec {len(sources)} sources référencées")
        return point.id
    except Exception as e:
        print(f"   ⚠️ Erreur stockage synthèse Qdrant: {e}")
        return None



# ============================================
# 11. TEST API
# ============================================

def test_apis():
    """Teste les APIs"""
    print("🔍 TEST DES APIS")
    print("="*60)

    manquants = missing_settings()
    if manquants:
        print(f"   ⚠️ Variables non configurées dans .env : {', '.join(manquants)}")

    # Test Groq
    try:
        print("1. Test Groq...", end="", flush=True)
        messages = [{"role": "user", "content": "Test"}]
        payload = {"model": GROQ_MODEL, "messages": messages, "max_tokens": 10}
        response = requests.post(GROQ_API_URL, headers=HEADERS, json=payload, timeout=10)
        if response.status_code == 200:
            print(" ✅ OK")
        else:
            print(f" ⚠️ Code {response.status_code}")
    except Exception as e:
        print(f" ❌ {e}")

    # Test Firecrawl
    print("2. Test Firecrawl...", end="", flush=True)
    try:
        engine = FirecrawlSearchEngine()
        results = engine.search("test", limit=1)
        if results:
            print(f" ✅ {len(results)} résultats")
        else:
            print(" ⚠️ Aucun résultat")
    except Exception as e:
        print(f" ❌ {e}")

    print("="*60)


#ajouter un article danq qdrant

def ajouter_article_qdrant(titre: str, resume: str, url: str, source: str,
                             query_used: str, semantic_engine):
    """
    Ajoute un seul article dans la collection Qdrant.
    """
    texte = f"{titre} {resume}"
    embedding = semantic_engine.generate_embeddings(texte)

    point = PointStruct(
        id=str(uuid.uuid4()),
        vector=embedding.tolist(),
        payload={
            "type": "article",
            "title": titre,
            "resume": resume,
            "url": url,
            "source": source,
            "query_used": query_used,
            "date": datetime.now().isoformat()
        }
    )

    try:
        get_qdrant().upsert(collection_name=COLLECTION_NAME, points=[point])
        print(f"✅ Article '{titre}' ajouté dans Qdrant")
        return point.id
    except Exception as e:
        print(f"   ⚠️ Erreur ajout article Qdrant: {e}")
        return None



# ============================================
# 12. EXÉCUTION PRINCIPALE
# ============================================



def main():
    print("="*70)
    print("🔬 RECHERCHE SÉMANTIQUE AVEC LLM & FIRECRAWL")
    print("   • Génération de requêtes par Groq")
    print("   • Recherche web avec Firecrawl")
    print("   • Recherche académique (OpenAlex)")
    print("   • Embeddings TF-IDF")
    print("   • Classement sémantique")
    print("   • Résumé automatique")
    print("="*70)

    test_apis()
    setup_collection()

    print("\n" + "="*70)
    print("📝 SAISIE DES REQUÊTES")
    print("   Entrez vos requêtes (tapez 'fin' pour terminer)")
    print("="*70)

    searcher = UnifiedSearchWithLLM()



    while True:
        user_query = input("\n🔎 Entrez votre sujet de recherche : ").strip()

        if user_query.lower() == 'fin':
            print("👋 Fin de la session.")
            break

        if not user_query:
            print("⚠️ Requête vide, réessayez.")
            continue

        result_data = searcher.search(user_query, limit=5)
        display_results(result_data)
        if result_data.get("from_cache") and len(result_data.get("results", [])) < 2:
            print("\nℹ️ Résultat unique depuis le cache — pas de synthèse générée")
        else:
            display_synthese(result_data, searcher.semantic_engine, top_n=3)





if __name__ == "__main__":
    main()
