"""A snapshot of EBI's nucleotide BLAST database codes.

Captured from `GET /ncbiblast/parameterdetails/database` on 2026-08-25. The live
catalogue is always preferred; this exists so that validation still works when
EBI is unreachable, and so the offline test suite can check a composed code
against something real rather than against a hand-written guess.

Regenerate with `scripts/refresh_ena_snapshot.py`.
"""
from __future__ import annotations

#: code -> human-readable label, nucleotide context only.
SNAPSHOT: dict[str, str] = {
    'cdp': 'COVID-19 Consensus Sequences',
    'em_all': 'ENA Sequence',
    'em_cds': 'ENA Coding Sequence',
    'em_cds_env': 'ENA Coding Sequence Environmental',
    'em_cds_est_inv': 'ENA Coding Sequence EST Invertebrate',
    'em_cds_est_mam': 'ENA Coding Sequence EST Mammal',
    'em_cds_est_pln': 'ENA Coding Sequence EST Plant',
    'em_cds_fun': 'ENA Coding Sequence Fungi',
    'em_cds_gss_env': 'ENA Coding Sequence GSS Environmental',
    'em_cds_gss_inv': 'ENA Coding Sequence GSS Invertebrate',
    'em_cds_gss_pln': 'ENA Coding Sequence GSS Plant',
    'em_cds_gss_pro': 'ENA Coding Sequence GSS Prokaryote',
    'em_cds_htc_env': 'ENA Coding Sequence HTC Environmental',
    'em_cds_htc_fun': 'ENA Coding Sequence HTC Fungi',
    'em_cds_htc_hum': 'ENA Coding Sequence HTC Human',
    'em_cds_htc_inv': 'ENA Coding Sequence HTC Invertebrate',
    'em_cds_htc_mam': 'ENA Coding Sequence HTC Mammal',
    'em_cds_htc_mus': 'ENA Coding Sequence HTC Mouse',
    'em_cds_htc_pln': 'ENA Coding Sequence HTC Plant',
    'em_cds_htc_pro': 'ENA Coding Sequence HTC Prokaryote',
    'em_cds_htc_rod': 'ENA Coding Sequence HTC Rodent',
    'em_cds_htc_vrl': 'ENA Coding Sequence HTC Viral',
    'em_cds_htc_vrt': 'ENA Coding Sequence HTC Vertebrate',
    'em_cds_htg_env': 'ENA Coding Sequence HTG Environmental',
    'em_cds_htg_fun': 'ENA Coding Sequence HTG Fungi',
    'em_cds_htg_hum': 'ENA Coding Sequence HTG Human',
    'em_cds_htg_inv': 'ENA Coding Sequence HTG Invertebrate',
    'em_cds_htg_mam': 'ENA Coding Sequence HTG Mammal',
    'em_cds_htg_mus': 'ENA Coding Sequence HTG Mouse',
    'em_cds_htg_phg': 'ENA Coding Sequence HTG Phage',
    'em_cds_htg_pln': 'ENA Coding Sequence HTG Plant',
    'em_cds_htg_pro': 'ENA Coding Sequence HTG Prokaryote',
    'em_cds_htg_rod': 'ENA Coding Sequence HTG Rodent',
    'em_cds_htg_vrl': 'ENA Coding Sequence HTG Viral',
    'em_cds_htg_vrt': 'ENA Coding Sequence HTG Vertebrate',
    'em_cds_hum': 'ENA Coding Sequence Human',
    'em_cds_inv': 'ENA Coding Sequence Invertebrate',
    'em_cds_mam': 'ENA Coding Sequence Mammal',
    'em_cds_mus': 'ENA Coding Sequence Mouse',
    'em_cds_pat_env': 'ENA Coding Sequence Patent Environmental',
    'em_cds_pat_fun': 'ENA Coding Sequence Patent Fungi',
    'em_cds_pat_hum': 'ENA Coding Sequence Patent Human',
    'em_cds_pat_inv': 'ENA Coding Sequence Patent Invertebrate',
    'em_cds_pat_mam': 'ENA Coding Sequence Patent Mammal',
    'em_cds_pat_mus': 'ENA Coding Sequence Patent Mouse',
    'em_cds_pat_phg': 'ENA Coding Sequence Patent Phage',
    'em_cds_pat_pln': 'ENA Coding Sequence Patent Plant',
    'em_cds_pat_pro': 'ENA Coding Sequence Patent Prokaryote',
    'em_cds_pat_rod': 'ENA Coding Sequence Patent Rodent',
    'em_cds_pat_syn': 'ENA Coding Sequence Patent Synthetic',
    'em_cds_pat_unc': 'ENA Coding Sequence Patent Unclassified',
    'em_cds_pat_vrl': 'ENA Coding Sequence Patent Viral',
    'em_cds_pat_vrt': 'ENA Coding Sequence Patent Vertebrate',
    'em_cds_phg': 'ENA Coding Sequence Phage',
    'em_cds_pln': 'ENA Coding Sequence Plant',
    'em_cds_pro': 'ENA Coding Sequence Prokaryote',
    'em_cds_rod': 'ENA Coding Sequence Rodent',
    'em_cds_std_env': 'ENA Coding Sequence Standard Environmental',
    'em_cds_std_fun': 'ENA Coding Sequence Standard Fungi',
    'em_cds_std_hum': 'ENA Coding Sequence Standard Human',
    'em_cds_std_inv': 'ENA Coding Sequence Standard Invertebrate',
    'em_cds_std_mam': 'ENA Coding Sequence Standard Mammal',
    'em_cds_std_mus': 'ENA Coding Sequence Standard Mouse',
    'em_cds_std_phg': 'ENA Coding Sequence Standard Phage',
    'em_cds_std_pln': 'ENA Coding Sequence Standard Plant',
    'em_cds_std_pro': 'ENA Coding Sequence Standard Prokaryote',
    'em_cds_std_rod': 'ENA Coding Sequence Standard Rodent',
    'em_cds_std_syn': 'ENA Coding Sequence Standard Synthetic',
    'em_cds_std_tgn': 'ENA Coding Sequence Standard Transgenic',
    'em_cds_std_unc': 'ENA Coding Sequence Standard Unclassified',
    'em_cds_std_vrl': 'ENA Coding Sequence Standard Viral',
    'em_cds_std_vrt': 'ENA Coding Sequence Standard Vertebrate',
    'em_cds_sts_hum': 'ENA Coding Sequence STS Human',
    'em_cds_sts_mam': 'ENA Coding Sequence STS Mammal',
    'em_cds_sts_pln': 'ENA Coding Sequence STS Plant',
    'em_cds_sts_vrt': 'ENA Coding Sequence STS Vertebrate',
    'em_cds_syn': 'ENA Coding Sequence Synthetic',
    'em_cds_tgn': 'ENA Coding Sequence Transgenic',
    'em_cds_tsa_fun': 'ENA Coding Sequence TSA Fungi',
    'em_cds_tsa_inv': 'ENA Coding Sequence TSA Invertebrate',
    'em_cds_tsa_mam': 'ENA Coding Sequence TSA Mammal',
    'em_cds_tsa_pln': 'ENA Coding Sequence TSA Plant',
    'em_cds_tsa_vrt': 'ENA Coding Sequence TSA Vertebrate',
    'em_cds_unc': 'ENA Coding Sequence Unclassified',
    'em_cds_vrl': 'ENA Coding Sequence Viral',
    'em_cds_vrt': 'ENA Coding Sequence Vertebrate',
    'em_env': 'ENA Sequence Environmental',
    'em_est': 'ENA Sequence Expressed Sequence Tag',
    'em_est_env': 'ENA Sequence EST Environmental',
    'em_est_fun': 'ENA Sequence EST Fungi',
    'em_est_hum': 'ENA Sequence EST Human',
    'em_est_inv': 'ENA Sequence EST Invertebrate',
    'em_est_mam': 'ENA Sequence EST Mammal',
    'em_est_mus': 'ENA Sequence EST Mouse',
    'em_est_pln': 'ENA Sequence EST Plant',
    'em_est_pro': 'ENA Sequence EST Prokaryote',
    'em_est_rod': 'ENA Sequence EST Rodent',
    'em_est_vrl': 'ENA Sequence EST Viral',
    'em_est_vrt': 'ENA Sequence EST Vertebrate',
    'em_fun': 'ENA Sequence Fungi',
    'em_geo_rel': 'ENA Geospatial Sequence',
    'em_gss': 'ENA Sequence Genome Survey Sequence',
    'em_gss_env': 'ENA Sequence GSS Environmental',
    'em_gss_fun': 'ENA Sequence GSS Fungi',
    'em_gss_hum': 'ENA Sequence GSS Human',
    'em_gss_inv': 'ENA Sequence GSS Invertebrate',
    'em_gss_mam': 'ENA Sequence GSS Mammal',
    'em_gss_mus': 'ENA Sequence GSS Mouse',
    'em_gss_phg': 'ENA Sequence GSS Phage',
    'em_gss_pln': 'ENA Sequence GSS Plant',
    'em_gss_pro': 'ENA Sequence GSS Prokaryote',
    'em_gss_rod': 'ENA Sequence GSS Rodent',
    'em_gss_tgn': 'ENA Sequence GSS Transgenic',
    'em_gss_vrl': 'ENA Sequence GSS Viral',
    'em_gss_vrt': 'ENA Sequence GSS Vertebrate',
    'em_htc': 'ENA Sequence High Throughput cDNA',
    'em_htc_env': 'ENA Sequence HTC Environmental',
    'em_htc_fun': 'ENA Sequence HTC Fungi',
    'em_htc_hum': 'ENA Sequence HTC Human',
    'em_htc_inv': 'ENA Sequence HTC Invertebrate',
    'em_htc_mam': 'ENA Sequence HTC Mammal',
    'em_htc_mus': 'ENA Sequence HTC Mouse',
    'em_htc_pln': 'ENA Sequence HTC Plant',
    'em_htc_pro': 'ENA Sequence HTC Prokaryote',
    'em_htc_rod': 'ENA Sequence HTC Rodent',
    'em_htc_vrl': 'ENA Sequence HTC Viral',
    'em_htc_vrt': 'ENA Sequence HTC Vertebrate',
    'em_htg': 'ENA Sequence High Throughput Genome',
    'em_htg_env': 'ENA Sequence HTG Environmental',
    'em_htg_fun': 'ENA Sequence HTG Fungi',
    'em_htg_hum': 'ENA Sequence HTG Human',
    'em_htg_inv': 'ENA Sequence HTG Invertebrate',
    'em_htg_mam': 'ENA Sequence HTG Mammal',
    'em_htg_mus': 'ENA Sequence HTG Mouse',
    'em_htg_phg': 'ENA Sequence HTG Phage',
    'em_htg_pln': 'ENA Sequence HTG Plant',
    'em_htg_pro': 'ENA Sequence HTG Prokaryote',
    'em_htg_rod': 'ENA Sequence HTG Rodent',
    'em_htg_vrl': 'ENA Sequence HTG Viral',
    'em_htg_vrt': 'ENA Sequence HTG Vertebrate',
    'em_hum': 'ENA Sequence Human',
    'em_inv': 'ENA Sequence Invertebrate',
    'em_mam': 'ENA Sequence Mammal',
    'em_mus': 'ENA Sequence Mouse',
    'em_ncr': 'ENA Non-coding Sequence',
    'em_ncr_env': 'ENA Non-coding Sequence Environmental',
    'em_ncr_est_mam': 'ENA Non-coding Sequence EST Mammal',
    'em_ncr_est_rod': 'ENA Non-coding Sequence EST Rodent',
    'em_ncr_est_vrt': 'ENA Non-coding Sequence EST Vertebrate',
    'em_ncr_fun': 'ENA Non-coding Sequence Fungi',
    'em_ncr_gss_fun': 'ENA Non-coding Sequence GSS Fungi',
    'em_ncr_gss_inv': 'ENA Non-coding Sequence GSS Invertebrate',
    'em_ncr_htc_hum': 'ENA Non-coding Sequence HTC Human',
    'em_ncr_htc_inv': 'ENA Non-coding Sequence HTC Invertebrate',
    'em_ncr_htc_pln': 'ENA Non-coding Sequence HTC Plant',
    'em_ncr_htg_env': 'ENA Non-coding Sequence HTG Environmental',
    'em_ncr_htg_fun': 'ENA Non-coding Sequence HTG Fungi',
    'em_ncr_htg_inv': 'ENA Non-coding Sequence HTG Invertebrate',
    'em_ncr_htg_mam': 'ENA Non-coding Sequence HTG Mammal',
    'em_ncr_htg_mus': 'ENA Non-coding Sequence HTG Mouse',
    'em_ncr_htg_phg': 'ENA Non-coding Sequence HTG Phage',
    'em_ncr_htg_pln': 'ENA Non-coding Sequence HTG Plant',
    'em_ncr_htg_pro': 'ENA Non-coding Sequence HTG Prokaryote',
    'em_ncr_htg_vrl': 'ENA Non-coding Sequence HTG Viral',
    'em_ncr_hum': 'ENA Non-coding Sequence Human',
    'em_ncr_inv': 'ENA Non-coding Sequence Invertebrate',
    'em_ncr_mam': 'ENA Non-coding Sequence Mammal',
    'em_ncr_mus': 'ENA Non-coding Sequence Mouse',
    'em_ncr_pat_fun': 'ENA Non-coding Sequence Patent Fungi',
    'em_ncr_pat_hum': 'ENA Non-coding Sequence Patent Human',
    'em_ncr_pat_inv': 'ENA Non-coding Sequence Patent Invertebrate',
    'em_ncr_pat_mus': 'ENA Non-coding Sequence Patent Mouse',
    'em_ncr_pat_pln': 'ENA Non-coding Sequence Patent Plant',
    'em_ncr_pat_pro': 'ENA Non-coding Sequence Patent Prokaryote',
    'em_ncr_pat_syn': 'ENA Non-coding Sequence Patent Synthetic',
    'em_ncr_pat_unc': 'ENA Non-coding Sequence Patent Unclassified',
    'em_ncr_pat_vrl': 'ENA Non-coding Sequence Patent Viral',
    'em_ncr_phg': 'ENA Non-coding Sequence Phage',
    'em_ncr_pln': 'ENA Non-coding Sequence Plant',
    'em_ncr_pro': 'ENA Non-coding Sequence Prokaryote',
    'em_ncr_rod': 'ENA Non-coding Sequence Rodent',
    'em_ncr_std_env': 'ENA Non-coding Sequence Standard Environmental',
    'em_ncr_std_fun': 'ENA Non-coding Sequence Standard Fungi',
    'em_ncr_std_hum': 'ENA Non-coding Sequence Standard Human',
    'em_ncr_std_inv': 'ENA Non-coding Sequence Standard Invertebrate',
    'em_ncr_std_mam': 'ENA Non-coding Sequence Standard Mammal',
    'em_ncr_std_mus': 'ENA Non-coding Sequence Standard Mouse',
    'em_ncr_std_phg': 'ENA Non-coding Sequence Standard Phage',
    'em_ncr_std_pln': 'ENA Non-coding Sequence Standard Plant',
    'em_ncr_std_pro': 'ENA Non-coding Sequence Standard Prokaryote',
    'em_ncr_std_rod': 'ENA Non-coding Sequence Standard Rodent',
    'em_ncr_std_syn': 'ENA Non-coding Sequence Standard Synthetic',
    'em_ncr_std_tgn': 'ENA Non-coding Sequence Standard Transgenic',
    'em_ncr_std_unc': 'ENA Non-coding Sequence Standard Unclassified',
    'em_ncr_std_vrl': 'ENA Non-coding Sequence Standard Viral',
    'em_ncr_std_vrt': 'ENA Non-coding Sequence Standard Vertebrate',
    'em_ncr_sts_fun': 'ENA Non-coding Sequence STS Fungi',
    'em_ncr_sts_hum': 'ENA Non-coding Sequence STS Human',
    'em_ncr_sts_vrt': 'ENA Non-coding Sequence STS Vertebrate',
    'em_ncr_syn': 'ENA Non-coding Sequence Synthetic',
    'em_ncr_tgn': 'ENA Non-coding Sequence Transgenic',
    'em_ncr_tsa_inv': 'ENA Non-coding Sequence TSA Invertebrate',
    'em_ncr_unc': 'ENA Non-coding Sequence Unclassified',
    'em_ncr_vrl': 'ENA Non-coding Sequence Viral',
    'em_ncr_vrt': 'ENA Non-coding Sequence Vertebrate',
    'em_pat': 'ENA Sequence Patent',
    'em_pat_env': 'ENA Sequence Patent Environmental',
    'em_pat_fun': 'ENA Sequence Patent Fungi',
    'em_pat_hum': 'ENA Sequence Patent Human',
    'em_pat_inv': 'ENA Sequence Patent Invertebrate',
    'em_pat_mam': 'ENA Sequence Patent Mammal',
    'em_pat_mus': 'ENA Sequence Patent Mouse',
    'em_pat_phg': 'ENA Sequence Patent Phage',
    'em_pat_pln': 'ENA Sequence Patent Plant',
    'em_pat_pro': 'ENA Sequence Patent Prokaryote',
    'em_pat_rod': 'ENA Sequence Patent Rodent',
    'em_pat_syn': 'ENA Sequence Patent Synthetic',
    'em_pat_unc': 'ENA Sequence Patent Unclassified',
    'em_pat_vrl': 'ENA Sequence Patent Viral',
    'em_pat_vrt': 'ENA Sequence Patent Vertebrate',
    'em_phg': 'ENA Sequence Phage',
    'em_pln': 'ENA Sequence Plant',
    'em_pro': 'ENA Sequence Prokaryote',
    'em_rod': 'ENA Sequence Rodent',
    'em_rrna': 'ENA Ribosomal Sequence',
    'em_spacer': 'ENA Spacer Sequence',
    'em_std': 'ENA Sequence Standard',
    'em_std_env': 'ENA Sequence Standard Environmental',
    'em_std_fun': 'ENA Sequence Standard Fungi',
    'em_std_hum': 'ENA Sequence Standard Human',
    'em_std_inv': 'ENA Sequence Standard Invertebrate',
    'em_std_mam': 'ENA Sequence Standard Mammal',
    'em_std_mus': 'ENA Sequence Standard Mouse',
    'em_std_phg': 'ENA Sequence Standard Phage',
    'em_std_pln': 'ENA Sequence Standard Plant',
    'em_std_pro': 'ENA Sequence Standard Prokaryote',
    'em_std_rod': 'ENA Sequence Standard Rodent',
    'em_std_syn': 'ENA Sequence Standard Synthetic',
    'em_std_tgn': 'ENA Sequence Standard Transgenic',
    'em_std_unc': 'ENA Sequence Standard Unclassified',
    'em_std_vrl': 'ENA Sequence Standard Viral',
    'em_std_vrt': 'ENA Sequence Standard Vertebrate',
    'em_sts': 'ENA Sequence Sequence Tagged Site',
    'em_sts_env': 'ENA Sequence STS Environmental',
    'em_sts_fun': 'ENA Sequence STS Fungi',
    'em_sts_hum': 'ENA Sequence STS Human',
    'em_sts_inv': 'ENA Sequence STS Invertebrate',
    'em_sts_mam': 'ENA Sequence STS Mammal',
    'em_sts_mus': 'ENA Sequence STS Mouse',
    'em_sts_pln': 'ENA Sequence STS Plant',
    'em_sts_pro': 'ENA Sequence STS Prokaryote',
    'em_sts_rod': 'ENA Sequence STS Rodent',
    'em_sts_vrt': 'ENA Sequence STS Vertebrate',
    'em_syn': 'ENA Sequence Synthetic',
    'em_tgn': 'ENA Sequence Transgenic',
    'em_tsa': 'ENA Sequence Transcriptome Shotgun Assembly',
    'em_tsa_env': 'ENA Sequence TSA Environmental',
    'em_tsa_fun': 'ENA Sequence TSA Fungi',
    'em_tsa_inv': 'ENA Sequence TSA Invertebrate',
    'em_tsa_mam': 'ENA Sequence TSA Mammal',
    'em_tsa_pln': 'ENA Sequence TSA Plant',
    'em_tsa_pro': 'ENA Sequence TSA Prokaryote',
    'em_tsa_rod': 'ENA Sequence TSA Rodent',
    'em_tsa_vrl': 'ENA Sequence TSA Viral',
    'em_tsa_vrt': 'ENA Sequence TSA Vertebrate',
    'em_unc': 'ENA Sequence Unclassified',
    'em_vrl': 'ENA Sequence Viral',
    'em_vrt': 'ENA Sequence Vertebrate',
    'emvec': 'ENA Sequence Vectors',
    'ensembl_covid/Sars_cov_2.ASM985889v3.cdna.all': 'EnsemblCOVID19 cdna sequences',
    'ensembl_covid/Sars_cov_2.ASM985889v3.dna.toplevel': 'EnsemblCOVID19 toplevel sequences',
    'ensembl_covid/Sars_cov_2.ASM985889v3.dna_rm.toplevel': 'EnsemblCOVID19 rm toplevel sequences',
    'imgthlacds': 'IMGT/HLA (cds)',
    'imgthlagen': 'IMGT/HLA (genomic)',
    'imgtligm': 'IMGT/LIGM-DB',
    'ipdkircds': 'IPD-KIR (cds)',
    'ipdkirgen': 'IPD-KIR (genomic)',
    'ipdmhccds': 'IPD-MHC (cds)',
    'ipdmhcgen': 'IPD-MHC (genomic)',
    'ipdnhkircds': 'IPD-NHKIR (cds)',
    'ipdnhkirgen': 'IPD-NHKIR (genomic)',
    'nrnl1': 'NR Patent DNAs Level-1',
    'nrnl2': 'NR Patent DNAs Level-2',
    'pdbna': 'Nucleotide Structure Sequences',
}
